spring:
  flyway:
    enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3307/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 139.224.35.86
    ## 发布确认模式开启
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/

